### PR TITLE
Update OFXcodeMenu-Info.plist

### PR DESCRIPTION
**Pull request by lewislepton**
added SIERRA xcode 8.1 UUID

### CODE REVIEW

**Comment by lewislepton** [comment]
though on looking xcode 8 has stopped folk from making sure plugins work. sad face indeed

**Comment by admsyn** [comment]
Yes indeed, it won't work 😢

**Comment by arturoc** [comment]
@admsyn perhaps we should close this repo or add a deprecation note in the readme? this issue comes up every few days lately

**Comment by arturoc** [comment]
just saw that there's already a deprecation note sorry :)

**Pull request closed without merging**
