### PR TITLE
xcode 6.3 uuid

### PR DESCRIPTION
**Pull request by grayfuse**
Me again! Love this tool, happy to help keep it up to date.

### CODE REVIEW

**Comment by admsyn** [comment]
Thanks :) The plugin [doesn't actually work with 6.3 yet](https://github.com/admsyn/OFPlugin/issues/31) but I'll pull this once I get it fixed.

**Comment by grayfuse** [comment]
All sleepygarden's doing (Michael Cornell), but updates in place to get OFPlugin working again in 6.3. Haven't tried this in previous versions of XCode, so this might be better folded into a branch other than master.

**Comment by admsyn** [comment]
Looks good, thanks @sleepygarden ! 

There's a bit of junk that got pulled in on the commits though (.DS_Store, .xcuserstate etc). I could rebase them out when I have a moment but can you submit a PR that just includes the necessary modifications?

**Comment by grayfuse** [comment]
Removed what I could, added a .gitignore but i'm sure it could use some additional items in it down the line.

**Comment by kylemcdonald** [comment]
woo thanks!

**Pull request merged**
